import json
def setup(vm,deploy,alice,bob,charlie,answer):
 vm.warp('2035-01-01T00:00:00+00:00');vm.sender=alice;c=deploy('contracts/contract.py');c.open_audit('permit-17','0x'+bob.hex(),'0x'+charlie.hex(),'Permit suspension 17','https://rules.example/appeals','https://decision.example/17',['FORUM','DEADLINE','METHOD'],600);vm.sender=charlie;vm.mock_web(r'rules\.example',{'status':200,'body':'Appeal to Review Board within 30 days by online form.'});vm.mock_web(r'decision\.example',{'status':200,'body':'Decision notice.'});vm.mock_llm(r'.*AppealLantern remedy-instruction audit.*',json.dumps(answer));c.inspect_notice('permit-17');return c
def test_defect_and_cure(direct_vm,direct_deploy,direct_alice,direct_bob,direct_charlie):
 bad={'missing_fields':['DEADLINE','METHOD'],'contradictory_fields':[],'forum':'Review Board','deadline_text':'UNKNOWN','filing_method':'UNKNOWN','summary':'Notice omits filing details.'};c=setup(direct_vm,direct_deploy,direct_alice,direct_bob,direct_charlie,bad);assert c.get_audit('permit-17')['state']=='DEFECTIVE';direct_vm.sender=direct_bob;direct_vm.clear_mocks();direct_vm.mock_web(r'rules\.example',{'status':200,'body':'Appeal to Review Board within 30 days by online form.'});direct_vm.mock_web(r'decision\.example',{'status':200,'body':'Appeal to Review Board within 30 days by online form.'});good={'missing_fields':[],'contradictory_fields':[],'forum':'Review Board','deadline_text':'30 days','filing_method':'online form','summary':'All remedy fields are stated.'};direct_vm.mock_llm(r'.*AppealLantern remedy-instruction audit.*',json.dumps(good));c.cure_notice('permit-17','https://decision.example/17-corrected');assert c.get_audit('permit-17')['state']=='CURED'
def test_role_origin_and_forged_result(direct_vm,direct_deploy,direct_alice,direct_bob,direct_charlie):
 good={'missing_fields':[],'contradictory_fields':[],'forum':'Review Board','deadline_text':'30 days','filing_method':'online form','summary':'Complete.'};direct_vm.warp('2035-01-01T00:00:00+00:00');direct_vm.sender=direct_alice;c=direct_deploy('contracts/contract.py');c.open_audit('x','0x'+direct_bob.hex(),'0x'+direct_charlie.hex(),'A sufficiently clear decision','https://rules.example/a','https://decision.example/a',['FORUM','DEADLINE','METHOD'],600);direct_vm.mock_web(r'rules\.example',{'status':200,'body':'rules'});direct_vm.mock_web(r'decision\.example',{'status':200,'body':'notice'});direct_vm.mock_llm(r'.*AppealLantern remedy-instruction audit.*',json.dumps(good));
 with direct_vm.expect_revert('independent reviewer'):c.inspect_notice('x')
 direct_vm.sender=direct_charlie;x=c.audits['X'];r=c._inspect(x,x.decision_url);assert direct_vm.run_validator(leader_result=r) is True;forged=dict(r);forged['forum']='Elsewhere';assert direct_vm.run_validator(leader_result=forged) is False
